name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        sudo apt-get install -qq lcov libboost-test-dev
        ./build.sh test
